### ISSUE TITLE
Allow line numbers globally

### ISSUE THREAD

**Issue by asavienko** [runtimeverification/k-web-theme#33] opened 2023-04-24 15:36 UTC
Add line numbers 

https://kframework.org/k-distribution/k-tutorial/1_basic/08_literate_programming/

![Image](https://user-images.githubusercontent.com/19416734/234046217-bbc3d95d-9f4b-4eff-b296-f614fb5c37d4.png)

**Comment by yiyi-wang-rv** [comment] 2023-04-25 02:22
@asavienko This is already fixed on our side. 

The issue is that the `k` repository didn't pass its `release` job, so github page deployment didn't run at all. That's why the K website is not updated. 

For example, https://github.com/runtimeverification/k/actions/runs/4786759844, you could see `GitHub Pages deployment` didn't run at all.

I would suggest someone working on `k` to help take a look. Maybe @radumereuta ? 

Thank you!

**Comment by radumereuta** [comment] 2023-04-25 20:02
@F-WRunTime is this related to your latest update to mvn paths?
```console
+ docker exec -t k-package-docker-test-jammy-6b4c63fbc7db8f79f49c97d76f5015998f5c7ef7 bash -c 'mkdir -p ~/.m2'
+ docker cp /home/github-runner/.m2/settings.xml 'k-package-docker-test-jammy-6b4c63fbc7db8f79f49c97d76f5015998f5c7ef7:~/.m2/settings.xml'
Error: No such container:path: k-package-docker-test-jammy-6b4c63fbc7db8f79f49c97d76f5015998f5c7ef7:~/.m2
```

**Comment by FWBlueWizard** [comment] 2023-04-26 06:30
This error should have been addressed [here](https://github.com/runtimeverification/k/pull/3351). 

But appears the tilde is not properly resolving. It appears it's just using the 'root' user in the container not sure that's the best solution though to assume root and copy it such that it runs 
docker cp <file> <container>:/root/.m2/settings.xml

**Comment by FWBlueWizard** [comment] 2023-04-26 06:45
Theoretically blocked by: 

- [x] https://github.com/runtimeverification/k/pull/3362

**Comment by FWBlueWizard** [comment] 2023-07-20 13:41
This still an issue? or can now be closed?

**Comment by radumereuta** [comment] 2023-07-21 15:21
Looking at the tutorial on the web page looks like it's solved
https://kframework.org/k-distribution/k-tutorial/1_basic/07_side_conditions/

**Closed as completed by radumereuta** 2023-07-21 15:21 UTC
